spring.application.name=horas-complementares
spring.datasource.url=jdbc:postgresql://localhost:5432/horas-complementares
spring.datasource.username=projeto
spring.datasource.password=ueceproject123#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

