spring.application.name=horas-complementares
spring.datasource.url=jdbc:postgresql://localhost:5432/projetoaps
spring.jpa.properties.hibernate.default_schema=schemaps
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456
api.security.token.secret=meu_segredo_super_secreto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

